import { Injectable } from '@angular/core';
import { HttpHeaders, HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class AppService {
  data:any = [
    {
      "subpremise": "",
      "street_number": 7300,
      "route": "Estero Boulevard",
      "neighborhood": "",
      "city_id": 4487,
      "county_id": 1370,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33931,
      "location_lat": 26.4123057,
      "location_lng": -81.9009712,
      "program_id": 4,
      "policy_no": "RC00017001",
      "original_zip_code": 33931,
      "formatted_address": "7300 Estero Blvd, Fort Myers Beach, FL 33931, USA",
      "policy_addr_id": 8956,
      "original_property_addr": "7300 ESTERO BLVD A",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4487,
      "original_county_id": 1370,
      "original_state_id": 113,
      "original_city": "Fort Myers Beach",
      "original_county": "Lee",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 7330,
      "route": "Estero Boulevard",
      "neighborhood": "",
      "city_id": 4487,
      "county_id": 1370,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33931,
      "location_lat": 26.412194,
      "location_lng": -81.9013046,
      "program_id": 4,
      "policy_no": "RC00018001",
      "original_zip_code": 33931,
      "formatted_address": "7330 Estero Blvd, Fort Myers Beach, FL 33931, USA",
      "policy_addr_id": 8957,
      "original_property_addr": "7330 ESTERO BLVD B",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4488,
      "original_county_id": 1370,
      "original_state_id": 113,
      "original_city": "Ft Myers Beach",
      "original_county": "Lee",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 7360,
      "route": "Estero Boulevard",
      "neighborhood": "",
      "city_id": 4487,
      "county_id": 1370,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33931,
      "location_lat": 26.4115189,
      "location_lng": -81.9010638,
      "program_id": 4,
      "policy_no": "RC00019001",
      "original_zip_code": 33931,
      "formatted_address": "7360 Estero Blvd, Fort Myers Beach, FL 33931, USA",
      "policy_addr_id": 8958,
      "original_property_addr": "7360 ESTERO BLVD- C",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4488,
      "original_county_id": 1370,
      "original_state_id": 113,
      "original_city": "Ft Myers Beach",
      "original_county": "Lee",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 19424,
      "route": "Gulf Boulevard",
      "neighborhood": "",
      "city_id": 4489,
      "county_id": 1371,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33785,
      "location_lat": 27.850025,
      "location_lng": -82.844534,
      "program_id": 4,
      "policy_no": "RC00007001",
      "original_zip_code": 33785,
      "formatted_address": "19424 Gulf Blvd, Indian Shores, FL 33785, USA",
      "policy_addr_id": 8959,
      "original_property_addr": "19424 GULF BLVD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4489,
      "original_county_id": 1371,
      "original_state_id": 113,
      "original_city": "Indian Shores",
      "original_county": "Pinellas",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 17040,
      "route": "Gulf Boulevard",
      "neighborhood": "",
      "city_id": 4490,
      "county_id": 1371,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33708,
      "location_lat": 27.8188837,
      "location_lng": -82.8250568,
      "program_id": 4,
      "policy_no": "RC00010001",
      "original_zip_code": 33708,
      "formatted_address": "17040 Gulf Blvd, North Redington Beach, FL 33708, USA",
      "policy_addr_id": 8960,
      "original_property_addr": "17040 GULF BLVD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4491,
      "original_county_id": 1371,
      "original_state_id": 113,
      "original_city": "N Redington Beach",
      "original_county": "Pinellas",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1875,
      "route": "Kalanianaole Avenue",
      "neighborhood": "",
      "city_id": 4492,
      "county_id": 1372,
      "state_id": 114,
      "country_id": 1,
      "zip_code": 96720,
      "location_lat": 19.7331247,
      "location_lng": -155.0269694,
      "program_id": 4,
      "policy_no": "RC00004001",
      "original_zip_code": 96720,
      "formatted_address": "1875 Kalanianaole Ave, Hilo, HI 96720, USA",
      "policy_addr_id": 8961,
      "original_property_addr": "1875 KALANIANAOLE AVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4492,
      "original_county_id": 1372,
      "original_state_id": 114,
      "original_city": "Hilo",
      "original_county": "Hawaii",
      "original_state": "HI",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 418,
      "route": "Carolina Beach Avenue North",
      "neighborhood": "",
      "city_id": 4493,
      "county_id": 1373,
      "state_id": 115,
      "country_id": 1,
      "zip_code": 28428,
      "location_lat": 34.0388706,
      "location_lng": -77.8898267,
      "program_id": 4,
      "policy_no": "RC00002001",
      "original_zip_code": 28428,
      "formatted_address": "418 Carolina Beach Ave N, Carolina Beach, NC 28428, USA",
      "policy_addr_id": 8962,
      "original_property_addr": "418 CAROLINA BEACH AVE N",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4493,
      "original_county_id": 1373,
      "original_state_id": 115,
      "original_city": "Carolina Beach",
      "original_county": "New Hanover",
      "original_state": "NC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 407,
      "route": "Carolina Beach Avenue South",
      "neighborhood": "",
      "city_id": 4493,
      "county_id": 1373,
      "state_id": 115,
      "country_id": 1,
      "zip_code": 28428,
      "location_lat": 34.0294096,
      "location_lng": -77.8938449,
      "program_id": 4,
      "policy_no": "RC00003001",
      "original_zip_code": 28428,
      "formatted_address": "407 Carolina Beach Ave S, Carolina Beach, NC 28428, USA",
      "policy_addr_id": 8963,
      "original_property_addr": "407 CAROLINA BEACH AVE S",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4493,
      "original_county_id": 1373,
      "original_state_id": 115,
      "original_city": "Carolina Beach",
      "original_county": "New Hanover",
      "original_state": "NC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 409,
      "route": "Carolina Beach Avenue South",
      "neighborhood": "",
      "city_id": 4493,
      "county_id": 1373,
      "state_id": 115,
      "country_id": 1,
      "zip_code": 28428,
      "location_lat": 34.0291351,
      "location_lng": -77.8939331,
      "program_id": 4,
      "policy_no": "RC00008001",
      "original_zip_code": 28428,
      "formatted_address": "409 Carolina Beach Ave S, Carolina Beach, NC 28428, USA",
      "policy_addr_id": 8964,
      "original_property_addr": "409 CAROLINA BEACH AVE S",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4493,
      "original_county_id": 1373,
      "original_state_id": 115,
      "original_city": "Carolina Beach",
      "original_county": "New Hanover",
      "original_state": "NC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1423,
      "route": "South Lake Park Boulevard",
      "neighborhood": "",
      "city_id": 4493,
      "county_id": 1373,
      "state_id": 115,
      "country_id": 1,
      "zip_code": 28428,
      "location_lat": 34.017197,
      "location_lng": -77.8986665,
      "program_id": 4,
      "policy_no": "RC00011001",
      "original_zip_code": 28428,
      "formatted_address": "1423 S Lake Park Blvd, Carolina Beach, NC 28428, USA",
      "policy_addr_id": 8965,
      "original_property_addr": "1423 S LAKE PARK BLVD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4493,
      "original_county_id": 1373,
      "original_state_id": 115,
      "original_city": "Carolina Beach",
      "original_county": "New Hanover",
      "original_state": "NC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 32,
      "route": "Vendue Range",
      "neighborhood": "French Quarter",
      "city_id": 4494,
      "county_id": 1374,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29401,
      "location_lat": 32.7789097,
      "location_lng": -79.9268344,
      "program_id": 4,
      "policy_no": "RC00021001",
      "original_zip_code": 29401,
      "formatted_address": "32 Vendue Range, Charleston, SC 29401, USA",
      "policy_addr_id": 8966,
      "original_property_addr": "32 VENDUE RANGE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4494,
      "original_county_id": 1374,
      "original_state_id": 116,
      "original_city": "Charleston",
      "original_county": "Charleston",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 669,
      "route": "Retreat Beach Circle",
      "neighborhood": "",
      "city_id": 4495,
      "county_id": 1375,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29585,
      "location_lat": 33.4795523,
      "location_lng": -79.0898125,
      "program_id": 4,
      "policy_no": "RC00020001",
      "original_zip_code": 29585,
      "formatted_address": "669 Retreat Beach Cir, Pawleys Island, SC 29585, USA",
      "policy_addr_id": 8967,
      "original_property_addr": "669 RETREAT BEACH CIRCLE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4495,
      "original_county_id": 1375,
      "original_state_id": 116,
      "original_city": "Pawleys Island",
      "original_county": "Georgetown",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "N TOWER",
      "street_number": 6900,
      "route": "North Ocean Boulevard",
      "neighborhood": "",
      "city_id": 4496,
      "county_id": 1376,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29572,
      "location_lat": 33.7387272,
      "location_lng": -78.8208768,
      "program_id": 4,
      "policy_no": "RC00005001",
      "original_zip_code": 29572,
      "formatted_address": "6900 N Ocean Blvd N TOWER, Myrtle Beach, SC 29572, USA",
      "policy_addr_id": 8968,
      "original_property_addr": "6900 N OCEAN BL, N TOWER",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4496,
      "original_county_id": 1376,
      "original_state_id": 116,
      "original_city": "Myrtle Beach",
      "original_county": "Horry",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 208,
      "route": "North Ocean Boulevard",
      "neighborhood": "",
      "city_id": 4497,
      "county_id": 1376,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29582,
      "location_lat": 33.8194779,
      "location_lng": -78.669025,
      "program_id": 4,
      "policy_no": "RC00012001",
      "original_zip_code": 29582,
      "formatted_address": "208 N Ocean Blvd, North Myrtle Beach, SC 29582, USA",
      "policy_addr_id": 8969,
      "original_property_addr": "208 N. OCEAN BLVD, B-1",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4498,
      "original_county_id": 1376,
      "original_state_id": 116,
      "original_city": "N. Myrtle Beach",
      "original_county": "Horry",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 108,
      "route": "North Ocean Boulevard",
      "neighborhood": "",
      "city_id": 4497,
      "county_id": 1376,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29582,
      "location_lat": 33.8194779,
      "location_lng": -78.669025,
      "program_id": 4,
      "policy_no": "RC00013001",
      "original_zip_code": 29582,
      "formatted_address": "108 N Ocean Blvd, North Myrtle Beach, SC 29582, USA",
      "policy_addr_id": 8970,
      "original_property_addr": "108 N. OCEAN BLVD, B-2",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4498,
      "original_county_id": 1376,
      "original_state_id": 116,
      "original_city": "N. Myrtle Beach",
      "original_county": "Horry",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "B",
      "street_number": 3,
      "route": "North Ocean Boulevard",
      "neighborhood": "",
      "city_id": 4497,
      "county_id": 1376,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29582,
      "location_lat": 33.8274058,
      "location_lng": -78.6459567,
      "program_id": 4,
      "policy_no": "RC00014001",
      "original_zip_code": 29582,
      "formatted_address": "3 N Ocean Blvd B, North Myrtle Beach, SC 29582, USA",
      "policy_addr_id": 8971,
      "original_property_addr": "210 N. OCEAN BLVD, B-3",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4498,
      "original_county_id": 1376,
      "original_state_id": 116,
      "original_city": "N. Myrtle Beach",
      "original_county": "Horry",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 206,
      "route": "North Ocean Boulevard",
      "neighborhood": "",
      "city_id": 4497,
      "county_id": 1376,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29582,
      "location_lat": 33.838903,
      "location_lng": -78.606352,
      "program_id": 4,
      "policy_no": "RC00015001",
      "original_zip_code": 29582,
      "formatted_address": "206 N Ocean Blvd, North Myrtle Beach, SC 29582, USA",
      "policy_addr_id": 8972,
      "original_property_addr": "206 N. OCEAN BLVD, B-4",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4498,
      "original_county_id": 1376,
      "original_state_id": 116,
      "original_city": "N. Myrtle Beach",
      "original_county": "Horry",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 202,
      "route": "North Ocean Boulevard",
      "neighborhood": "",
      "city_id": 4497,
      "county_id": 1376,
      "state_id": 116,
      "country_id": 1,
      "zip_code": 29582,
      "location_lat": 33.819563,
      "location_lng": -78.6698928,
      "program_id": 4,
      "policy_no": "RC00016001",
      "original_zip_code": 29582,
      "formatted_address": "202 N Ocean Blvd, North Myrtle Beach, SC 29582, USA",
      "policy_addr_id": 8973,
      "original_property_addr": "202 N. OCEAN BLVD, B-5",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4498,
      "original_county_id": 1376,
      "original_state_id": 116,
      "original_city": "N. Myrtle Beach",
      "original_county": "Horry",
      "original_state": "SC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 15,
      "route": "Somerset Street",
      "neighborhood": "Clearwater Beach",
      "city_id": 4499,
      "county_id": 1371,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33767,
      "location_lat": 27.988862,
      "location_lng": -82.8274558,
      "program_id": 4,
      "policy_no": "RC00023001",
      "original_zip_code": 33767,
      "formatted_address": "15 Somerset St, Clearwater Beach, FL 33767, USA",
      "policy_addr_id": 8974,
      "original_property_addr": "15 SOMERSET STREET",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4499,
      "original_county_id": 1371,
      "original_state_id": 113,
      "original_city": "Clearwater",
      "original_county": "Pinellas",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 616,
      "route": "Carolina Beach Avenue North",
      "neighborhood": "",
      "city_id": 4493,
      "county_id": 1373,
      "state_id": 115,
      "country_id": 1,
      "zip_code": 28428,
      "location_lat": 34.0416126,
      "location_lng": -77.8887328,
      "program_id": 4,
      "policy_no": "RC00022001",
      "original_zip_code": 28428,
      "formatted_address": "616 Carolina Beach Ave N, Carolina Beach, NC 28428, USA",
      "policy_addr_id": 8975,
      "original_property_addr": "616 CAROLINA BEACH AVE N",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4493,
      "original_county_id": 1373,
      "original_state_id": 115,
      "original_city": "Carolina Beach",
      "original_county": "New Hanover",
      "original_state": "NC",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3550,
      "route": "South Ocean Boulevard",
      "neighborhood": "",
      "city_id": 4500,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33480,
      "location_lat": 26.6118996,
      "location_lng": -80.0384661,
      "program_id": 4,
      "policy_no": "RC00024001",
      "original_zip_code": 33480,
      "formatted_address": "3550 S Ocean Blvd, Palm Beach, FL 33480, USA",
      "policy_addr_id": 8976,
      "original_property_addr": "3550 S. OCEAN BLVD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4501,
      "original_county_id": 1377,
      "original_state_id": 113,
      "original_city": "S. Palm Beach",
      "original_county": "Palm Beach",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 2463,
      "route": "Jamaica Way",
      "neighborhood": "Marina Faire",
      "city_id": 4502,
      "county_id": 1378,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 94577,
      "location_lat": 37.697532,
      "location_lng": -122.1808799,
      "program_id": 6,
      "policy_no": "04FL00040AA-00",
      "original_zip_code": 94577,
      "formatted_address": "2463 Jamaica Way, San Leandro, CA 94577, USA",
      "policy_addr_id": 8977,
      "original_property_addr": "2463 JAMAICA WAY",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4502,
      "original_county_id": 1378,
      "original_state_id": 117,
      "original_city": "San Leandro",
      "original_county": "Alameda",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 7500,
      "route": "Bailey Road",
      "neighborhood": "",
      "city_id": 4503,
      "county_id": 1379,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95531,
      "location_lat": 41.8803849,
      "location_lng": -124.147154,
      "program_id": 6,
      "policy_no": "04FL00001AA-00",
      "original_zip_code": 95531,
      "formatted_address": "7500 Bailey Rd, Crescent City, CA 95531, USA",
      "policy_addr_id": 8978,
      "original_property_addr": "7500 BAILEY RD.",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4503,
      "original_county_id": 1379,
      "original_state_id": 117,
      "original_city": "Crescent City",
      "original_county": "Del Norte",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 4444,
      "route": "Bay School Road",
      "neighborhood": "Pacific",
      "city_id": 4504,
      "county_id": 1380,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95521,
      "location_lat": 40.880377,
      "location_lng": -124.123335,
      "program_id": 6,
      "policy_no": "04FL00012AA-00",
      "original_zip_code": 95521,
      "formatted_address": "4444 Bay School Rd, Arcata, CA 95521, USA",
      "policy_addr_id": 8979,
      "original_property_addr": "4444 BAY SCHOOL RD - MAIN HOUSE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4504,
      "original_county_id": 1380,
      "original_state_id": 117,
      "original_city": "Arcata",
      "original_county": "Humboldt",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 4444,
      "route": "Bay School Road",
      "neighborhood": "Pacific",
      "city_id": 4504,
      "county_id": 1380,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95521,
      "location_lat": 40.880377,
      "location_lng": -124.123335,
      "program_id": 6,
      "policy_no": "04FL00013AA-00",
      "original_zip_code": 95521,
      "formatted_address": "4444 Bay School Rd, Arcata, CA 95521, USA",
      "policy_addr_id": 8980,
      "original_property_addr": "4444 BAY SCHOOL RD - LARGE BARN",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4504,
      "original_county_id": 1380,
      "original_state_id": 117,
      "original_city": "Arcata",
      "original_county": "Humboldt",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 4444,
      "route": "Bay School Road",
      "neighborhood": "Pacific",
      "city_id": 4504,
      "county_id": 1380,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95521,
      "location_lat": 40.880377,
      "location_lng": -124.123335,
      "program_id": 6,
      "policy_no": "04FL00014AA-00",
      "original_zip_code": 95521,
      "formatted_address": "4444 Bay School Rd, Arcata, CA 95521, USA",
      "policy_addr_id": 8981,
      "original_property_addr": "4444 BAY SCHOOL RD - SMALL BARN",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4504,
      "original_county_id": 1380,
      "original_state_id": 117,
      "original_city": "Arcata",
      "original_county": "Humboldt",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 6848,
      "route": "California 36",
      "neighborhood": "",
      "city_id": 4505,
      "county_id": 1380,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95528,
      "location_lat": 40.5298032,
      "location_lng": -124.0391028,
      "program_id": 6,
      "policy_no": "04FL00015AA-00",
      "original_zip_code": 95528,
      "formatted_address": "6848 CA-36, Carlotta, CA 95528, USA",
      "policy_addr_id": 8982,
      "original_property_addr": "6848 STATE HIGHWAY 36",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4505,
      "original_county_id": 1380,
      "original_state_id": 117,
      "original_city": "Carlotta",
      "original_county": "Humboldt",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": "",
      "route": "North Fortuna Boulevard",
      "neighborhood": "",
      "city_id": 4506,
      "county_id": 1380,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95540,
      "location_lat": 40.5947155,
      "location_lng": -124.1468492,
      "program_id": 6,
      "policy_no": "04FL00023AA-00",
      "original_zip_code": 95540,
      "formatted_address": "N Fortuna Blvd, Fortuna, CA 95540, USA",
      "policy_addr_id": 8983,
      "original_property_addr": "620 A & B NORTH FORTUNA BLVD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4506,
      "original_county_id": 1380,
      "original_state_id": 117,
      "original_city": "Fortuna",
      "original_county": "Humboldt",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1805,
      "route": "Monterey Street",
      "neighborhood": "",
      "city_id": 4507,
      "county_id": 1381,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93305,
      "location_lat": 35.3765944,
      "location_lng": -118.9740678,
      "program_id": 6,
      "policy_no": "04FL00004AA-00",
      "original_zip_code": 93305,
      "formatted_address": "1805 Monterey St, Bakersfield, CA 93305, USA",
      "policy_addr_id": 8984,
      "original_property_addr": "1805 MONTEREY ST",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4507,
      "original_county_id": 1381,
      "original_state_id": 117,
      "original_city": "Bakersfield",
      "original_county": "Kern",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "APT 611",
      "street_number": 645,
      "route": "West 9th Street",
      "neighborhood": "Downtown Los Angeles",
      "city_id": 4508,
      "county_id": 1382,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 90015,
      "location_lat": 34.0458143,
      "location_lng": -118.2605963,
      "program_id": 6,
      "policy_no": "04FL00034AA-00",
      "original_zip_code": 90015,
      "formatted_address": "645 W 9th St APT 611, Los Angeles, CA 90015, USA",
      "policy_addr_id": 8985,
      "original_property_addr": "645 W 9TH STREET #611",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4508,
      "original_county_id": 1382,
      "original_state_id": 117,
      "original_city": "Los Angeles",
      "original_county": "Los Angeles",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 2297,
      "route": "Pasetta Drive",
      "neighborhood": "",
      "city_id": 4509,
      "county_id": 1383,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95050,
      "location_lat": 37.3651916,
      "location_lng": -121.9643079,
      "program_id": 6,
      "policy_no": "04FL00036AA-00",
      "original_zip_code": 95050,
      "formatted_address": "2297 Pasetta Dr, Santa Clara, CA 95050, USA",
      "policy_addr_id": 8986,
      "original_property_addr": "2297 PASETTA DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4509,
      "original_county_id": 1383,
      "original_state_id": 117,
      "original_city": "Santa Clara",
      "original_county": "Santa Clara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 2299,
      "route": "Pasetta Drive",
      "neighborhood": "",
      "city_id": 4509,
      "county_id": 1383,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95050,
      "location_lat": 37.3653233,
      "location_lng": -121.9646189,
      "program_id": 6,
      "policy_no": "04FL00037AA-00",
      "original_zip_code": 95050,
      "formatted_address": "2299 Pasetta Dr, Santa Clara, CA 95050, USA",
      "policy_addr_id": 8987,
      "original_property_addr": "2299 PASETTA DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4509,
      "original_county_id": 1383,
      "original_state_id": 117,
      "original_city": "Santa Clara",
      "original_county": "Santa Clara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": 3319,
      "street_number": 3321,
      "route": "Agate Drive",
      "neighborhood": "",
      "city_id": 4509,
      "county_id": 1383,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95051,
      "location_lat": 37.3700854,
      "location_lng": -121.9881435,
      "program_id": 6,
      "policy_no": "04FL00020AA-00",
      "original_zip_code": 95051,
      "formatted_address": "3321 Agate Dr #3319, Santa Clara, CA 95051, USA",
      "policy_addr_id": 8988,
      "original_property_addr": "3319 & 3321 AGATE DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4509,
      "original_county_id": 1383,
      "original_state_id": 117,
      "original_city": "Santa Clara",
      "original_county": "Santa Clara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 13635,
      "route": "Lowrey Road",
      "neighborhood": "",
      "city_id": 4510,
      "county_id": 1384,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 96080,
      "location_lat": 40.016694,
      "location_lng": -122.529913,
      "program_id": 6,
      "policy_no": "04FL00029AA-00",
      "original_zip_code": 96080,
      "formatted_address": "13635 Lowrey Rd, Red Bluff, CA 96080, USA",
      "policy_addr_id": 8989,
      "original_property_addr": "13635 LOWERY RD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4510,
      "original_county_id": 1384,
      "original_state_id": 117,
      "original_city": "Red Bluff",
      "original_county": "Tehama",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 619,
      "route": "East Harold Avenue",
      "neighborhood": "",
      "city_id": 4511,
      "county_id": 1385,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93292,
      "location_lat": 36.3446939,
      "location_lng": -119.286179,
      "program_id": 6,
      "policy_no": "04FL00035AA-00",
      "original_zip_code": 93292,
      "formatted_address": "619 E Harold Ave, Visalia, CA 93292, USA",
      "policy_addr_id": 8990,
      "original_property_addr": "619 EAST HAROLD AVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4511,
      "original_county_id": 1385,
      "original_state_id": 117,
      "original_city": "Visalia",
      "original_county": "Tulare",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 742,
      "route": "Southwest 3rd Place",
      "neighborhood": "",
      "city_id": 4512,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33004,
      "location_lat": 26.0455095,
      "location_lng": -80.1506429,
      "program_id": 6,
      "policy_no": "09FL00005AA-00",
      "original_zip_code": 33004,
      "formatted_address": "742 SW 3rd Pl, Dania Beach, FL 33004, USA",
      "policy_addr_id": 8991,
      "original_property_addr": "742 SW 3 PLACE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4513,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Dania",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1243,
      "route": "Garfield Street",
      "neighborhood": "Hollywood Lakes",
      "city_id": 4514,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33019,
      "location_lat": 26.0223091,
      "location_lng": -80.1325214,
      "program_id": 6,
      "policy_no": "09FL00031AA-00",
      "original_zip_code": 33019,
      "formatted_address": "1243 Garfield St, Hollywood, FL 33019, USA",
      "policy_addr_id": 8992,
      "original_property_addr": "1243 GARFIELD ST",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4514,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Hollywood",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 11821,
      "route": "Southwest 13th Court",
      "neighborhood": "",
      "city_id": 4515,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33025,
      "location_lat": 25.9978463,
      "location_lng": -80.30435,
      "program_id": 6,
      "policy_no": "09FL00011AA-00",
      "original_zip_code": 33025,
      "formatted_address": "11821 SW 13th Ct, Pembroke Pines, FL 33025, USA",
      "policy_addr_id": 8993,
      "original_property_addr": "11821 SW 13TH CT",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4514,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Hollywood",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 10480,
      "route": "Waves Way",
      "neighborhood": "",
      "city_id": 4516,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33076,
      "location_lat": 26.3456799,
      "location_lng": -80.2702899,
      "program_id": 6,
      "policy_no": "09FL00045AA-00",
      "original_zip_code": 33076,
      "formatted_address": "10480 Waves Way, Parkland, FL 33076, USA",
      "policy_addr_id": 8994,
      "original_property_addr": "10480 WAVES WAY",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4516,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Parkland",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1131,
      "route": "Northwest 14th Court",
      "neighborhood": "Lauderdale Manors",
      "city_id": 4517,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33311,
      "location_lat": 26.1443878,
      "location_lng": -80.1575907,
      "program_id": 6,
      "policy_no": "09FL00008AA-00",
      "original_zip_code": 33311,
      "formatted_address": "1131 NW 14th Ct, Fort Lauderdale, FL 33311, USA",
      "policy_addr_id": 8995,
      "original_property_addr": "1131 NW 14 CT",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4517,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Fort Lauderdale",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3125,
      "route": "Southwest 12th Place",
      "neighborhood": "South Fort Lauderdale",
      "city_id": 4517,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33312,
      "location_lat": 26.1063493,
      "location_lng": -80.1870052,
      "program_id": 6,
      "policy_no": "09FL00006AA-00",
      "original_zip_code": 33312,
      "formatted_address": "3125 SW 12th Pl, Fort Lauderdale, FL 33312, USA",
      "policy_addr_id": 8996,
      "original_property_addr": "3125 SW 12 PL",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4518,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Ft Lauderdale",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1906,
      "route": "Southwest 8th Street",
      "neighborhood": "Melrose Manors",
      "city_id": 4517,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33312,
      "location_lat": 26.1114615,
      "location_lng": -80.1737697,
      "program_id": 6,
      "policy_no": "09FL00007AA-00",
      "original_zip_code": 33312,
      "formatted_address": "1906 SW 8th St, Fort Lauderdale, FL 33312, USA",
      "policy_addr_id": 8997,
      "original_property_addr": "1906-08 SW 8th street",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4518,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Ft Lauderdale",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 651,
      "route": "Southwest 14th Court",
      "neighborhood": "",
      "city_id": 4519,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33441,
      "location_lat": 26.2989492,
      "location_lng": -80.1127819,
      "program_id": 6,
      "policy_no": "09FL00009AA-00",
      "original_zip_code": 33441,
      "formatted_address": "651 SW 14th Ct, Deerfield Beach, FL 33441, USA",
      "policy_addr_id": 8998,
      "original_property_addr": "651 SW 14TH CT",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4519,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Deerfield Beach",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 4072,
      "route": "Quarterhorse Court",
      "neighborhood": "Southside",
      "city_id": 4520,
      "county_id": 1387,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32223,
      "location_lat": 30.1395138,
      "location_lng": -81.6023285,
      "program_id": 6,
      "policy_no": "09FL00010AA-00",
      "original_zip_code": 32223,
      "formatted_address": "4072 Quarterhorse Ct, Jacksonville, FL 32223, USA",
      "policy_addr_id": 8999,
      "original_property_addr": "4072 QUARTERHORSE COURT",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4520,
      "original_county_id": 1387,
      "original_state_id": 113,
      "original_city": "Jacksonville",
      "original_county": "Duval",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 4304,
      "route": "West Robin Lane",
      "neighborhood": "Beach Park",
      "city_id": 4521,
      "county_id": 1388,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33609,
      "location_lat": 27.9401005,
      "location_lng": -82.5166708,
      "program_id": 6,
      "policy_no": "09FL00033AA-00",
      "original_zip_code": 33609,
      "formatted_address": "4304 W Robin Ln, Tampa, FL 33609, USA",
      "policy_addr_id": 9000,
      "original_property_addr": "4304 ROBIN LANE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4521,
      "original_county_id": 1388,
      "original_state_id": 113,
      "original_city": "Tampa",
      "original_county": "Hillsborough",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3512,
      "route": "West Granada Street",
      "neighborhood": "Palma Ceia",
      "city_id": 4521,
      "county_id": 1388,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33629,
      "location_lat": 27.9209501,
      "location_lng": -82.5013526,
      "program_id": 6,
      "policy_no": "09FL00026AA-00",
      "original_zip_code": 33629,
      "formatted_address": "3512 W Granada St, Tampa, FL 33629, USA",
      "policy_addr_id": 9001,
      "original_property_addr": "3512 W GRANADA ST",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4521,
      "original_county_id": 1388,
      "original_state_id": 113,
      "original_city": "Tampa",
      "original_county": "Hillsborough",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 8787,
      "route": "Northwest 168th Lane",
      "neighborhood": "",
      "city_id": 4522,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33018,
      "location_lat": 25.926763,
      "location_lng": -80.3435255,
      "program_id": 6,
      "policy_no": "09FL00039AA-00",
      "original_zip_code": 33018,
      "formatted_address": "8787 NW 168th Ln, Hialeah, FL 33018, USA",
      "policy_addr_id": 9002,
      "original_property_addr": "8787 NW 168 LANE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4522,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Hialeah",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 25070,
      "route": "Southwest 122nd Place",
      "neighborhood": "",
      "city_id": 4523,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33032,
      "location_lat": 25.5325486,
      "location_lng": -80.3900393,
      "program_id": 6,
      "policy_no": "09FL00019AA-00",
      "original_zip_code": 33032,
      "formatted_address": "25070 SW 122nd Pl, Princeton, FL 33032, USA",
      "policy_addr_id": 9003,
      "original_property_addr": "25070 SW 122ND PL",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4524,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Homestead",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3120,
      "route": "Southeast 2nd Drive",
      "neighborhood": "",
      "city_id": 4524,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33033,
      "location_lat": 25.4684759,
      "location_lng": -80.4307516,
      "program_id": 6,
      "policy_no": "09FL00017AA-00",
      "original_zip_code": 33033,
      "formatted_address": "3120 SE 2nd Dr, Homestead, FL 33033, USA",
      "policy_addr_id": 9004,
      "original_property_addr": "3120 SE 2ND DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4524,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Homestead",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3241,
      "route": "Northwest 14th Street",
      "neighborhood": "Little Havana",
      "city_id": 4525,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33125,
      "location_lat": 25.7868772,
      "location_lng": -80.2487338,
      "program_id": 6,
      "policy_no": "09FL00024AA-00",
      "original_zip_code": 33125,
      "formatted_address": "3241 NW 14th St, Miami, FL 33125, USA",
      "policy_addr_id": 9005,
      "original_property_addr": "3241 NW 14TH ST",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 5051,
      "route": "North Kendall Drive",
      "neighborhood": "",
      "city_id": 4525,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33156,
      "location_lat": 25.6909062,
      "location_lng": -80.275557,
      "program_id": 6,
      "policy_no": "09FL00021AA-00",
      "original_zip_code": 33156,
      "formatted_address": "5051 N Kendall Dr, Miami, FL 33156, USA",
      "policy_addr_id": 9006,
      "original_property_addr": "5051 N KENDALL DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 18740,
      "route": "Southwest 92nd Avenue",
      "neighborhood": "",
      "city_id": 4526,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33157,
      "location_lat": 25.5923569,
      "location_lng": -80.3407408,
      "program_id": 6,
      "policy_no": "09FL00038AA-00",
      "original_zip_code": 33157,
      "formatted_address": "18740 SW 92nd Ave, Cutler Bay, FL 33157, USA",
      "policy_addr_id": 9007,
      "original_property_addr": "18740 SW 92 AVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4526,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Cutler Bay",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 14250,
      "route": "Southwest 73rd Court",
      "neighborhood": "",
      "city_id": 4527,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33158,
      "location_lat": 25.6382746,
      "location_lng": -80.3127364,
      "program_id": 6,
      "policy_no": "09FL00046AA-00",
      "original_zip_code": 33158,
      "formatted_address": "14250 SW 73rd Ct, Palmetto Bay, FL 33158, USA",
      "policy_addr_id": 9008,
      "original_property_addr": "14250 SW 73RD CT",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 10380,
      "route": "Southwest 115th Street",
      "neighborhood": "",
      "city_id": 4525,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33176,
      "location_lat": 25.6616302,
      "location_lng": -80.3627983,
      "program_id": 6,
      "policy_no": "09FL00018AA-00",
      "original_zip_code": 33176,
      "formatted_address": "10380 SW 115th St, Miami, FL 33176, USA",
      "policy_addr_id": 9009,
      "original_property_addr": "10380 SW 115TH STREET",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 655,
      "route": "Northeast 191st Terrace",
      "neighborhood": "",
      "city_id": 4525,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33179,
      "location_lat": 25.9518666,
      "location_lng": -80.1878225,
      "program_id": 6,
      "policy_no": "09FL00016AA-00",
      "original_zip_code": 33179,
      "formatted_address": "655 NE 191st Terrace, Miami, FL 33179, USA",
      "policy_addr_id": 9010,
      "original_property_addr": "655 NE 191 TERRACE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 627,
      "route": "Cherokee Circle",
      "neighborhood": "Southeast Orlando",
      "city_id": 4528,
      "county_id": 1390,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32801,
      "location_lat": 28.5338463,
      "location_lng": -81.36978,
      "program_id": 6,
      "policy_no": "09FL00044AA-00",
      "original_zip_code": 32801,
      "formatted_address": "627 Cherokee Cir, Orlando, FL 32801, USA",
      "policy_addr_id": 9011,
      "original_property_addr": "627 CHEROKEE CIR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4528,
      "original_county_id": 1390,
      "original_state_id": 113,
      "original_city": "Orlando",
      "original_county": "Orange",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 2770,
      "route": "Long Meadow Drive",
      "neighborhood": "",
      "city_id": 4529,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33414,
      "location_lat": 26.6392978,
      "location_lng": -80.2227638,
      "program_id": 6,
      "policy_no": "09FL00032AA-00",
      "original_zip_code": 33414,
      "formatted_address": "2770 Long Meadow Dr, Wellington, FL 33414, USA",
      "policy_addr_id": 9012,
      "original_property_addr": "2770 LONG MEADOW DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4529,
      "original_county_id": 1377,
      "original_state_id": 113,
      "original_city": "Wellington",
      "original_county": "Palm Beach",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3412,
      "route": "Place Valencay",
      "neighborhood": "",
      "city_id": 4530,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33445,
      "location_lat": 26.4710673,
      "location_lng": -80.1087243,
      "program_id": 6,
      "policy_no": "09FL00002AA-00",
      "original_zip_code": 33445,
      "formatted_address": "3412 Place Valencay, Delray Beach, FL 33445, USA",
      "policy_addr_id": 9013,
      "original_property_addr": "3412 PLACE VALENCAY",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4530,
      "original_county_id": 1377,
      "original_state_id": 113,
      "original_city": "Delray Beach",
      "original_county": "Palm Beach",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 15265,
      "route": "Seaglass Terrace Lane",
      "neighborhood": "",
      "city_id": 4530,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33446,
      "location_lat": 26.4468712,
      "location_lng": -80.1992264,
      "program_id": 6,
      "policy_no": "09FL00027AA-00",
      "original_zip_code": 33446,
      "formatted_address": "15265 Seaglass Terrace Ln, Delray Beach, FL 33446, USA",
      "policy_addr_id": 9014,
      "original_property_addr": "15265 SEAGLASS TERRACE LN",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4530,
      "original_county_id": 1377,
      "original_state_id": 113,
      "original_city": "Delray Beach",
      "original_county": "Palm Beach",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 6392,
      "route": "Boyd Lane",
      "neighborhood": "",
      "city_id": 4531,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33462,
      "location_lat": 26.5813017,
      "location_lng": -80.0814073,
      "program_id": 6,
      "policy_no": "09FL00022AA-00",
      "original_zip_code": 33462,
      "formatted_address": "6392 Boyd Ln, Lake Worth, FL 33462, USA",
      "policy_addr_id": 9015,
      "original_property_addr": "6392 BOYD LN",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4531,
      "original_county_id": 1377,
      "original_state_id": 113,
      "original_city": "Lake Worth",
      "original_county": "Palm Beach",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 8577,
      "route": "Laurel Drive",
      "neighborhood": "Bayou Club",
      "city_id": 4532,
      "county_id": 1371,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33782,
      "location_lat": 27.8498808,
      "location_lng": -82.7407197,
      "program_id": 6,
      "policy_no": "09FL00028AA-00",
      "original_zip_code": 33782,
      "formatted_address": "8577 Laurel Dr, Pinellas Park, FL 33782, USA",
      "policy_addr_id": 9016,
      "original_property_addr": "8577 LAUREL DRIVE NORTH",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4532,
      "original_county_id": 1371,
      "original_state_id": 113,
      "original_city": "Pinellas Park",
      "original_county": "Pinellas",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1522,
      "route": "Whisper Wind Lane",
      "neighborhood": "",
      "city_id": 4533,
      "county_id": 1371,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 34677,
      "location_lat": 28.0697629,
      "location_lng": -82.6825384,
      "program_id": 6,
      "policy_no": "09FL00003AA-00",
      "original_zip_code": 34677,
      "formatted_address": "1522 Whisper Wind Ln, Oldsmar, FL 34677, USA",
      "policy_addr_id": 9017,
      "original_property_addr": "1522 WHISPER WIND LANE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4533,
      "original_county_id": 1371,
      "original_state_id": 113,
      "original_city": "Oldsmar",
      "original_county": "Pinellas",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": "",
      "route": "Samuel Place",
      "neighborhood": "",
      "city_id": 4534,
      "county_id": 1391,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33837,
      "location_lat": 28.2253866,
      "location_lng": -81.5766751,
      "program_id": 6,
      "policy_no": "09FL00043AA-00",
      "original_zip_code": 33837,
      "formatted_address": "614 SAMUEL PLACE",
      "policy_addr_id": 9018,
      "original_property_addr": "614 SAMUEL PLACE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4534,
      "original_county_id": 1391,
      "original_state_id": 113,
      "original_city": "Davenport",
      "original_county": "Polk",
      "original_state": "FL",
      "flag_value": "U"
    },
    {
      "subpremise": "",
      "street_number": 431,
      "route": "Magpie Court",
      "neighborhood": "",
      "city_id": 4535,
      "county_id": 1391,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 34759,
      "location_lat": 28.096361,
      "location_lng": -81.4712595,
      "program_id": 6,
      "policy_no": "09FL00030AA-00",
      "original_zip_code": 34759,
      "formatted_address": "431 Magpie Ct, Kissimmee, FL 34759, USA",
      "policy_addr_id": 9019,
      "original_property_addr": "431 MAGPIE CT",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4535,
      "original_county_id": 1391,
      "original_state_id": 113,
      "original_city": "Kissimmee",
      "original_county": "Polk",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1045,
      "route": "Fox Creek Drive",
      "neighborhood": "",
      "city_id": 4536,
      "county_id": 1392,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 34240,
      "location_lat": 27.344638,
      "location_lng": -82.439033,
      "program_id": 6,
      "policy_no": "09FL00047AA-00",
      "original_zip_code": 34240,
      "formatted_address": "1045 Fox Creek Dr, Sarasota, FL 34240, USA",
      "policy_addr_id": 9020,
      "original_property_addr": "1045 FOX CREEK DRIVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4536,
      "original_county_id": 1392,
      "original_state_id": 113,
      "original_city": "Sarasota",
      "original_county": "Sarasota",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 22575,
      "route": "Monte Vista Drive",
      "neighborhood": "",
      "city_id": 4537,
      "county_id": 1382,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 90290,
      "location_lat": 34.086809,
      "location_lng": -118.613262,
      "program_id": 6,
      "policy_no": "04FL00051AA-00",
      "original_zip_code": 90290,
      "formatted_address": "22575 Monte Vista Dr, Topanga, CA 90290, USA",
      "policy_addr_id": 9021,
      "original_property_addr": "22575 MONTE VISTA DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4537,
      "original_county_id": 1382,
      "original_state_id": 117,
      "original_city": "Topanga",
      "original_county": "Los Angeles",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 37333,
      "route": "Turner Drive",
      "neighborhood": "",
      "city_id": 4538,
      "county_id": 1393,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32784,
      "location_lat": 28.8926275,
      "location_lng": -81.6746653,
      "program_id": 6,
      "policy_no": "09FL00050AA-00",
      "original_zip_code": 32784,
      "formatted_address": "37333 Turner Dr, Umatilla, FL 32784, USA",
      "policy_addr_id": 9022,
      "original_property_addr": "37333 TURNER DRIVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4538,
      "original_county_id": 1393,
      "original_state_id": 113,
      "original_city": "Umatilla",
      "original_county": "Lake",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 9601,
      "route": "Southwest 68th Avenue",
      "neighborhood": "",
      "city_id": 4539,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33156,
      "location_lat": 25.6814198,
      "location_lng": -80.3044879,
      "program_id": 6,
      "policy_no": "09FL00049AA-00",
      "original_zip_code": 33156,
      "formatted_address": "9601 SW 68th Ave, Pinecrest, FL 33156, USA",
      "policy_addr_id": 9023,
      "original_property_addr": "9601 SW 68 AVENUE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 11393,
      "route": "Southwest 65th Street",
      "neighborhood": "",
      "city_id": 4525,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33173,
      "location_lat": 25.707191,
      "location_lng": -80.377653,
      "program_id": 6,
      "policy_no": "09FL00048AA-00",
      "original_zip_code": 33173,
      "formatted_address": "11393 SW 65th St, Miami, FL 33173, USA",
      "policy_addr_id": 9024,
      "original_property_addr": "11393 SW 65TH ST",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1975,
      "route": "Becker Lane",
      "neighborhood": "",
      "city_id": 4506,
      "county_id": 1380,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95540,
      "location_lat": 40.5614949,
      "location_lng": -124.1455325,
      "program_id": 6,
      "policy_no": "04FL00057AA-00",
      "original_zip_code": 95540,
      "formatted_address": "1975 Becker Ln, Fortuna, CA 95540, USA",
      "policy_addr_id": 9025,
      "original_property_addr": "1975 BECKER LANE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4506,
      "original_county_id": 1380,
      "original_state_id": 117,
      "original_city": "Fortuna",
      "original_county": "Humboldt",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 21062,
      "route": "Strathmoor Lane",
      "neighborhood": "",
      "city_id": 4540,
      "county_id": 2343,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 92646,
      "location_lat": 33.6567491,
      "location_lng": -117.957324,
      "program_id": 6,
      "policy_no": "04FL00054AA-00",
      "original_zip_code": 92646,
      "formatted_address": "21062 Strathmoor Ln, Huntington Beach, CA 92646, USA",
      "policy_addr_id": 9026,
      "original_property_addr": "21062 STRATHMOOR LN",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4540,
      "original_county_id": 2343,
      "original_state_id": 117,
      "original_city": "Huntington Beach",
      "original_county": "Orange",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 21211,
      "route": "Lockhaven Circle",
      "neighborhood": "",
      "city_id": 4540,
      "county_id": 2343,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 92646,
      "location_lat": 33.6546941,
      "location_lng": -117.95618,
      "program_id": 6,
      "policy_no": "04FL00055AA-00",
      "original_zip_code": 92646,
      "formatted_address": "21211 Lockhaven Cir, Huntington Beach, CA 92646, USA",
      "policy_addr_id": 9027,
      "original_property_addr": "21211 LOCKHAVEN CIRCLE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4540,
      "original_county_id": 2343,
      "original_state_id": 117,
      "original_city": "Huntington Beach",
      "original_county": "Orange",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": 85,
      "street_number": 87,
      "route": "Scharff Avenue",
      "neighborhood": "Alum Rock",
      "city_id": 4541,
      "county_id": 1383,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 95116,
      "location_lat": 37.355894,
      "location_lng": -121.844223,
      "program_id": 6,
      "policy_no": "04FL00059AA-00",
      "original_zip_code": 95116,
      "formatted_address": "87 Scharff Ave #85, San Jose, CA 95116, USA",
      "policy_addr_id": 9028,
      "original_property_addr": "85 & 87 SCHARFF AVENUE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4541,
      "original_county_id": 1383,
      "original_state_id": 117,
      "original_city": "San Jose",
      "original_county": "Santa Clara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3000,
      "route": "Northwest 91st Street",
      "neighborhood": "",
      "city_id": 4525,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33147,
      "location_lat": 25.8563051,
      "location_lng": -80.2463382,
      "program_id": 6,
      "policy_no": "09FL00061AA-00",
      "original_zip_code": 33147,
      "formatted_address": "3000 NW 91st St, Miami, FL 33147, USA",
      "policy_addr_id": 9029,
      "original_property_addr": "3000 NW 91ST STREET",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4525,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Miami",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 6730,
      "route": "Southwest 112th Street",
      "neighborhood": "",
      "city_id": 4525,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33156,
      "location_lat": 25.6666093,
      "location_lng": -80.3037696,
      "program_id": 6,
      "policy_no": "09FL00052AA-00",
      "original_zip_code": 33156,
      "formatted_address": "6730 SW 112th St, Miami, FL 33156, USA",
      "policy_addr_id": 9030,
      "original_property_addr": "6730 SW 112TH ST",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4539,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "Pinecrest",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 19412,
      "route": "Northeast 17th Avenue",
      "neighborhood": "",
      "city_id": 4542,
      "county_id": 1389,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33179,
      "location_lat": 25.9440509,
      "location_lng": -80.1668573,
      "program_id": 6,
      "policy_no": "09FL00060AA-00",
      "original_zip_code": 33179,
      "formatted_address": "19412 NE 17th Ave, North Miami Beach, FL 33179, USA",
      "policy_addr_id": 9031,
      "original_property_addr": "19412 NE 17TH AVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4542,
      "original_county_id": 1389,
      "original_state_id": 113,
      "original_city": "North Miami Beach",
      "original_county": "Miami-Dade",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 19707,
      "route": "Bay Cove Drive",
      "neighborhood": "",
      "city_id": 4543,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33434,
      "location_lat": 26.3887867,
      "location_lng": -80.1611521,
      "program_id": 6,
      "policy_no": "09FL00053AA-00",
      "original_zip_code": 33434,
      "formatted_address": "19707 Bay Cove Dr, Boca Raton, FL 33434, USA",
      "policy_addr_id": 9032,
      "original_property_addr": "19707 BAY COVE DRIVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4543,
      "original_county_id": 1377,
      "original_state_id": 113,
      "original_city": "Boca Raton",
      "original_county": "Palm Beach",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 8820,
      "route": "Palm River Drive",
      "neighborhood": "",
      "city_id": 4531,
      "county_id": 1377,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33467,
      "location_lat": 26.5625385,
      "location_lng": -80.1879206,
      "program_id": 6,
      "policy_no": "09FL00056AA-00",
      "original_zip_code": 33467,
      "formatted_address": "8820 Palm River Dr, Lake Worth, FL 33467, USA",
      "policy_addr_id": 9033,
      "original_property_addr": "8820 PALM RIVER DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4531,
      "original_county_id": 1377,
      "original_state_id": 113,
      "original_city": "Lake Worth",
      "original_county": "Palm Beach",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 306,
      "route": "Bancario Road",
      "neighborhood": "",
      "city_id": 4544,
      "county_id": 1394,
      "state_id": 118,
      "country_id": 1,
      "zip_code": 72364,
      "location_lat": 35.2109292,
      "location_lng": -90.2088419,
      "program_id": 8,
      "policy_no": "AX00112001",
      "original_zip_code": 72364,
      "formatted_address": "306 Bancario Rd, Marion, AR 72364, USA",
      "policy_addr_id": 9034,
      "original_property_addr": "306 BANCARIO ROAD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4544,
      "original_county_id": 1394,
      "original_state_id": 118,
      "original_city": "Marion",
      "original_county": "Crittenden",
      "original_state": "AR",
      "flag_value": ""
    },
    {
      "subpremise": "BLDG #6",
      "street_number": 2302,
      "route": "North 27th Street",
      "neighborhood": "Camelback East Village",
      "city_id": 4545,
      "county_id": 1395,
      "state_id": 119,
      "country_id": 1,
      "zip_code": 85008,
      "location_lat": 33.4735699,
      "location_lng": -112.024326,
      "program_id": 8,
      "policy_no": "AX00096001",
      "original_zip_code": 85008,
      "formatted_address": "2302 N 27th St BLDG #6, Phoenix, AZ 85008, USA",
      "policy_addr_id": 9035,
      "original_property_addr": "2302 N 27TH ST BLDG #6",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4545,
      "original_county_id": 1395,
      "original_state_id": 119,
      "original_city": "Phoenix",
      "original_county": "Maricopa",
      "original_state": "AZ",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 3384,
      "route": "Stoneridge Lane",
      "neighborhood": "Sherman Oaks",
      "city_id": 4508,
      "county_id": 1382,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 90077,
      "location_lat": 34.1337546,
      "location_lng": -118.4589768,
      "program_id": 8,
      "policy_no": "AX00126001",
      "original_zip_code": 90077,
      "formatted_address": "3384 Stoneridge Ln, Los Angeles, CA 90077, USA",
      "policy_addr_id": 9036,
      "original_property_addr": "3384 STONE RIDGE LANE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4508,
      "original_county_id": 1382,
      "original_state_id": 117,
      "original_city": "Los Angeles",
      "original_county": "Los Angeles",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 2121,
      "route": "Oceanside Boulevard",
      "neighborhood": "Fire Mountain",
      "city_id": 4546,
      "county_id": 1396,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 92054,
      "location_lat": 33.1965932,
      "location_lng": -117.3509245,
      "program_id": 8,
      "policy_no": "AX00110001",
      "original_zip_code": 92683,
      "formatted_address": "2121 Oceanside Blvd, Oceanside, CA 92054, USA",
      "policy_addr_id": 9037,
      "original_property_addr": "2121 OCEANSIDE BLVD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4546,
      "original_county_id": 2343,
      "original_state_id": 117,
      "original_city": "Oceanside",
      "original_county": "Orange",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 486,
      "route": "Marsh Street",
      "neighborhood": "Downtown",
      "city_id": 4547,
      "county_id": 1397,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93401,
      "location_lat": 35.2767331,
      "location_lng": -120.6669479,
      "program_id": 8,
      "policy_no": "AX00124001",
      "original_zip_code": 93401,
      "formatted_address": "486 Marsh St, San Luis Obispo, CA 93401, USA",
      "policy_addr_id": 9038,
      "original_property_addr": "486 MARSH ST",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4547,
      "original_county_id": 1397,
      "original_state_id": 117,
      "original_city": "San Luis Obispo",
      "original_county": "San Luis Obispo",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 545,
      "route": "Higuera Street",
      "neighborhood": "Downtown",
      "city_id": 4547,
      "county_id": 1397,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93401,
      "location_lat": 35.2770465,
      "location_lng": -120.6672174,
      "program_id": 8,
      "policy_no": "AX00124002",
      "original_zip_code": 93401,
      "formatted_address": "545 Higuera St, San Luis Obispo, CA 93401, USA",
      "policy_addr_id": 9039,
      "original_property_addr": "545 HIGUERA STREET",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4547,
      "original_county_id": 1397,
      "original_state_id": 117,
      "original_city": "San Luis Obispo",
      "original_county": "San Luis Obispo",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": 1,
      "street_number": 4530,
      "route": "Carpinteria Avenue",
      "neighborhood": "",
      "city_id": 4548,
      "county_id": 1398,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93013,
      "location_lat": 34.4020218,
      "location_lng": -119.5270386,
      "program_id": 8,
      "policy_no": "AX00132001",
      "original_zip_code": 93013,
      "formatted_address": "4530 Carpinteria Ave #1, Carpinteria, CA 93013, USA",
      "policy_addr_id": 9040,
      "original_property_addr": "4530 CARPINTERIA AVE #1",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4548,
      "original_county_id": 1398,
      "original_state_id": 117,
      "original_city": "Carpinteria",
      "original_county": "Santa Barbara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": 2,
      "street_number": 4530,
      "route": "Carpinteria Avenue",
      "neighborhood": "",
      "city_id": 4548,
      "county_id": 1398,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93013,
      "location_lat": 34.4020218,
      "location_lng": -119.5270386,
      "program_id": 8,
      "policy_no": "AX00132002",
      "original_zip_code": 93013,
      "formatted_address": "4530 Carpinteria Ave #2, Carpinteria, CA 93013, USA",
      "policy_addr_id": 9041,
      "original_property_addr": "4530 CARPINTERIA AVE #2",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4548,
      "original_county_id": 1398,
      "original_state_id": 117,
      "original_city": "Carpinteria",
      "original_county": "Santa Barbara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": 3,
      "street_number": 4530,
      "route": "Carpinteria Avenue",
      "neighborhood": "",
      "city_id": 4548,
      "county_id": 1398,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93013,
      "location_lat": 34.4020218,
      "location_lng": -119.5270386,
      "program_id": 8,
      "policy_no": "AX00132003",
      "original_zip_code": 93013,
      "formatted_address": "4530 Carpinteria Ave #3, Carpinteria, CA 93013, USA",
      "policy_addr_id": 9042,
      "original_property_addr": "4530 CARPINTERIA AVE #3",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4548,
      "original_county_id": 1398,
      "original_state_id": 117,
      "original_city": "Carpinteria",
      "original_county": "Santa Barbara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": 4,
      "street_number": 4530,
      "route": "Carpinteria Avenue",
      "neighborhood": "",
      "city_id": 4548,
      "county_id": 1398,
      "state_id": 117,
      "country_id": 1,
      "zip_code": 93013,
      "location_lat": 34.4020218,
      "location_lng": -119.5270386,
      "program_id": 8,
      "policy_no": "AX00132004",
      "original_zip_code": 93013,
      "formatted_address": "4530 Carpinteria Ave #4, Carpinteria, CA 93013, USA",
      "policy_addr_id": 9043,
      "original_property_addr": "4530 CARPINTERIA AVE #4",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4548,
      "original_county_id": 1398,
      "original_state_id": 117,
      "original_city": "Carpinteria",
      "original_county": "Santa Barbara",
      "original_state": "CA",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 5,
      "route": "Surf Road",
      "neighborhood": "",
      "city_id": 4549,
      "county_id": 1399,
      "state_id": 120,
      "country_id": 1,
      "zip_code": "06880",
      "location_lat": 41.0971603,
      "location_lng": -73.3771095,
      "program_id": 8,
      "policy_no": "AX00093001",
      "original_zip_code": "06880",
      "formatted_address": "5 Surf Rd, Westport, CT 06880, USA",
      "policy_addr_id": 9044,
      "original_property_addr": "5 SURF ROAD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4549,
      "original_county_id": 1399,
      "original_state_id": 120,
      "original_city": "Westport",
      "original_county": "Fairfield",
      "original_state": "CT",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 6840,
      "route": "Pembroke Road",
      "neighborhood": "",
      "city_id": 4550,
      "county_id": 1386,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 33023,
      "location_lat": 25.994693,
      "location_lng": -80.225691,
      "program_id": 8,
      "policy_no": "AX00120001",
      "original_zip_code": 33023,
      "formatted_address": "6840 Pembroke Rd, Miramar, FL 33023, USA",
      "policy_addr_id": 9045,
      "original_property_addr": "6840 PEMBROKE RD",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4514,
      "original_county_id": 1386,
      "original_state_id": 113,
      "original_city": "Hollywood",
      "original_county": "Broward",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 2180,
      "route": "Northwest 12th Avenue",
      "neighborhood": "",
      "city_id": 4551,
      "county_id": 1400,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 34428,
      "location_lat": 28.916012,
      "location_lng": -82.6109142,
      "program_id": 8,
      "policy_no": "AX00156001",
      "original_zip_code": 34428,
      "formatted_address": "2180 NW 12th Ave, Crystal River, FL 34428, USA",
      "policy_addr_id": 9046,
      "original_property_addr": "2180 NW 12TH AVENUE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4551,
      "original_county_id": 1400,
      "original_state_id": 113,
      "original_city": "Crystal River",
      "original_county": "Citrus",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 1990,
      "route": "Seward Avenue",
      "neighborhood": "",
      "city_id": 4552,
      "county_id": 1401,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 34109,
      "location_lat": 26.2149731,
      "location_lng": -81.7786621,
      "program_id": 8,
      "policy_no": "AX00098001",
      "original_zip_code": 34109,
      "formatted_address": "1990 Seward Ave, Naples, FL 34109, USA",
      "policy_addr_id": 9047,
      "original_property_addr": "1990 SEWARD AVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4552,
      "original_county_id": 1401,
      "original_state_id": 113,
      "original_city": "Naples",
      "original_county": "Collier",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 409,
      "route": "1st Avenue North",
      "neighborhood": "Old Naples",
      "city_id": 4552,
      "county_id": 1401,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 34102,
      "location_lat": 26.1479449,
      "location_lng": -81.8025263,
      "program_id": 8,
      "policy_no": "AX00157001",
      "original_zip_code": 34102,
      "formatted_address": "409 1st Ave N, Naples, FL 34102, USA",
      "policy_addr_id": 9048,
      "original_property_addr": "409 1ST AVE N",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4552,
      "original_county_id": 1401,
      "original_state_id": 113,
      "original_city": "Naples",
      "original_county": "Collier",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": 100,
      "street_number": 2865,
      "route": "Mayport Road",
      "neighborhood": "North Beach",
      "city_id": 4520,
      "county_id": 1387,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32233,
      "location_lat": 30.368866,
      "location_lng": -81.410101,
      "program_id": 8,
      "policy_no": "AX00105001",
      "original_zip_code": 32233,
      "formatted_address": "2865 Mayport Rd #100, Jacksonville, FL 32233, USA",
      "policy_addr_id": 9049,
      "original_property_addr": "2865 MAYPORT RD UNIT 100",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4520,
      "original_county_id": 1387,
      "original_state_id": 113,
      "original_city": "Jacksonville",
      "original_county": "Duval",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": 200,
      "street_number": 2865,
      "route": "Mayport Road",
      "neighborhood": "North Beach",
      "city_id": 4520,
      "county_id": 1387,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32233,
      "location_lat": 30.368866,
      "location_lng": -81.410101,
      "program_id": 8,
      "policy_no": "AX00105002",
      "original_zip_code": 32233,
      "formatted_address": "2865 Mayport Rd #200, Jacksonville, FL 32233, USA",
      "policy_addr_id": 9050,
      "original_property_addr": "2865 MAYPORT RD UNIT 200",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4520,
      "original_county_id": 1387,
      "original_state_id": 113,
      "original_city": "Jacksonville",
      "original_county": "Duval",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": 300,
      "street_number": 2865,
      "route": "Mayport Road",
      "neighborhood": "North Beach",
      "city_id": 4520,
      "county_id": 1387,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32233,
      "location_lat": 30.368866,
      "location_lng": -81.410101,
      "program_id": 8,
      "policy_no": "AX00105003",
      "original_zip_code": 32233,
      "formatted_address": "2865 Mayport Rd #300, Jacksonville, FL 32233, USA",
      "policy_addr_id": 9051,
      "original_property_addr": "2865 MAYPORT RD UNIT 300",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4520,
      "original_county_id": 1387,
      "original_state_id": 113,
      "original_city": "Jacksonville",
      "original_county": "Duval",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": 400,
      "street_number": 2865,
      "route": "Mayport Road",
      "neighborhood": "North Beach",
      "city_id": 4520,
      "county_id": 1387,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32233,
      "location_lat": 30.368866,
      "location_lng": -81.410101,
      "program_id": 8,
      "policy_no": "AX00105004",
      "original_zip_code": 32233,
      "formatted_address": "2865 Mayport Rd #400, Jacksonville, FL 32233, USA",
      "policy_addr_id": 9052,
      "original_property_addr": "2865 MAYPORT RD UNIT 400",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4520,
      "original_county_id": 1387,
      "original_state_id": 113,
      "original_city": "Jacksonville",
      "original_county": "Duval",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 4812,
      "route": "West Deer Lake Drive",
      "neighborhood": "Windy Hill",
      "city_id": 4520,
      "county_id": 1387,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32246,
      "location_lat": 30.2598637,
      "location_lng": -81.5549131,
      "program_id": 8,
      "policy_no": "AX00152001",
      "original_zip_code": 32246,
      "formatted_address": "4812 W Deer Lake Dr, Jacksonville, FL 32246, USA",
      "policy_addr_id": 9053,
      "original_property_addr": "4812 DEER LAKE DRIVE",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4520,
      "original_county_id": 1387,
      "original_state_id": 113,
      "original_city": "Jacksonville",
      "original_county": "Duval",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 411,
      "route": "West Garden Street",
      "neighborhood": "Downtown",
      "city_id": 4553,
      "county_id": 1402,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32502,
      "location_lat": 30.4113089,
      "location_lng": -87.2227188,
      "program_id": 8,
      "policy_no": "AX00104001",
      "original_zip_code": 32502,
      "formatted_address": "411 W Garden St, Pensacola, FL 32502, USA",
      "policy_addr_id": 9054,
      "original_property_addr": "411 W GARDEN STREET",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4553,
      "original_county_id": 1402,
      "original_state_id": 113,
      "original_city": "Pensacola",
      "original_county": "Escambia",
      "original_state": "FL",
      "flag_value": ""
    },
    {
      "subpremise": "",
      "street_number": 16313,
      "route": "Perdido Key Drive",
      "neighborhood": "",
      "city_id": 4553,
      "county_id": 1402,
      "state_id": 113,
      "country_id": 1,
      "zip_code": 32507,
      "location_lat": 30.285684,
      "location_lng": -87.492124,
      "program_id": 8,
      "policy_no": "AX00142001",
      "original_zip_code": 32507,
      "formatted_address": "16313 Perdido Key Dr, Pensacola, FL 32507, USA",
      "policy_addr_id": 9055,
      "original_property_addr": "16313 PERDIDO KEY DR",
      "original_property_addr1": "",
      "is_standardized": "True",
      "non_standard_fields": "",
      "original_city_id": 4553,
      "original_county_id": 1402,
      "original_state_id": 113,
      "original_city": "Pensacola",
      "original_county": "Escambia",
      "original_state": "FL",
      "flag_value": ""
    }
  ];
  constructor(private httpClient : HttpClient) { }

  checkCredential(){
      const headers = new HttpHeaders();
      headers.append('Access-Control-Allow-Headers', 'Content-Type');
      headers.append('Access-Control-Allow-Methods', 'POST');
      headers.append('Access-Control-Allow-Origin', '*');
      // return  this.httpClient.get<any[]>( 'http://localhost:8080/test/csv',{ headers });
      return this.data;
  }
  
}
